---
# Update Time: 2024-2-1 21:10
version: "3.4"

x-defines:
  service-common: &service-common-ref
    networks: [network_cluster]
    restart: on-failure
  env-common: &env-common-ref
    NO_PROXY: ${NO_PROXY:-localhost,127.0.0.1,::1}
    TZ: ${TZ:-Asia/Shanghai}    
  env-proxy: &env-proxy-ref
    HTTP_PROXY: ${OPENCLASH_HTTP_PROXY}
    HTTPS_PROXY: ${OPENCLASH_HTTP_PROXY}
    http_proxy: ${OPENCLASH_HTTP_PROXY}
    https_proxy: ${OPENCLASH_HTTP_PROXY}
  deploy-common: &deploy-common-ref
    mode: replicated
    replicas: 1
    restart_policy:
      condition: on-failure
      delay: 5s      
  placement-default: &placement-default-ref
    placement:
      constraints:
        - node.labels.type == vm
        - node.labels.resource == true
  driver-common: &driver-common-ref
    type: nfs
    o: addr=${NFS_SERVER},rw,nfsvers=4
  driver-media-main: &driver-media-main-ref
    type: nfs
    o: addr=${MEDIA_SERVER},rw,nfsvers=4
  driver-media-ext: &driver-media-ext-ref
    type: nfs
    o: addr=${MEDIA_EXT_SERVER},rw,nfsvers=4
  driver-iso: &driver-iso-ref
    type: nfs
    o: addr=${ISO_DEVICE},rw,nfsvers=4


services:
  # ------------------------------------------------------------
  # Transmission下载器
  # ------------------------------------------------------------
  transmission:
    <<: *service-common-ref
    image: registry.${DOMAIN_SWARM}:${EXTERNAL_PORT}/chisbread/transmission:version-3.00-r13.1
    environment:
      <<: *env-common-ref
      PUID: ${TR_PUID}
      PGID: ${TR_PGID}
      USERNAME: ${TR_USERNAME}
      PASSWORD: ${TR_PASSWORD}
    volumes:
      - nfs_transmission_config:/config
      - nfs_transmission_main_downloads:/media
      - nfs_transmission_ext_downloads:/media_ext
      - nfs_transmission_watch:/watch
    logging:
      driver: fluentd
      options:
        tag: docker.resource.transmissionn
        fluentd-async-connect: "true"
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.transmission.rule=Host(`pt.${DOMAIN_SWARM}`,`pt.${DOMAIN_EMERGENCY}`)
        - traefik.http.routers.transmission.entrypoints=websecure
        - traefik.http.routers.transmission.service=transmission
        - traefik.http.routers.transmission.middlewares=auth,normal-chain@file
        - traefik.http.services.transmission.loadbalancer.server.port=9091
        # - traefik.tcp.routers.torrent.rule=HostSNI(`*`)
        # - traefik.tcp.routers.torrent.entrypoints=torrent
        # - traefik.tcp.routers.torrent.service=torrent
        # - traefik.tcp.services.torrent.loadbalancer.server.port=51413
        - homepage.group=Application
        - homepage.name=Transmission
        - homepage.icon=transmission.png
        - homepage.href=https://pt.${DOMAIN_SWARM}:${EXTERNAL_PORT}/
        - homepage.description=PT下载器
        - homepage.siteMonitor=http://transmission:9091
        - homepage.weight=20
        - homepage.widget.type=transmission
        - homepage.widget.url=https://pt.${DOMAIN_SWARM}:${EXTERNAL_PORT}
        - homepage.widget.username=${TR_USERNAME}
        - homepage.widget.password=${TR_PASSWORD}
      <<: [*deploy-common-ref, *placement-default-ref]

  # ------------------------------------------------------------
  # Qbittorrent下载器
  # ------------------------------------------------------------
  qbittorrent:
    <<: *service-common-ref
    image: registry.${DOMAIN_SWARM}:${EXTERNAL_PORT}/linuxserver/qbittorrent:4.6.5
    environment:
      <<: *env-common-ref
      PUID: ${QB_PUID}
      PGID: ${QB_PGID}
      # UMASK_SET: 022    # （可选）默认022
      # WEBUI_PORT: 4  # WEB UI 端口
    volumes:
      - nfs_qbittorrent_config:/config
      - nfs_qbittorrent_main_downloads:/media
      - nfs_qbittorrent_ext_downloads:/media_ext
    logging:
      driver: fluentd
      options:
        tag: docker.resource.qbittorrent
        fluentd-async-connect: "true"
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.qbittorrent.rule=Host(`qb.${DOMAIN_SWARM}`,`qb.${DOMAIN_EMERGENCY}`)
        - traefik.http.routers.qbittorrent.entrypoints=websecure
        - traefik.http.routers.qbittorrent.service=qbittorrent
        - traefik.http.routers.qbittorrent.middlewares=auth,normal-chain@file
        - traefik.http.services.qbittorrent.loadbalancer.server.port=8080
        # - traefik.tcp.routers.qb_pt.rule=HostSNI(`*`)
        # - traefik.tcp.routers.qb_pt.entrypoints=qb_pt
        # - traefik.tcp.routers.qb_pt.service=qb_pt
        # - traefik.tcp.services.qb_pt.loadbalancer.server.port=6881
        - homepage.group=Application
        - homepage.name=Qbittorrent
        - homepage.icon=qbittorrent.png
        - homepage.href=https://qb.${DOMAIN_SWARM}:${EXTERNAL_PORT}/
        - homepage.description=PT下载器
        - homepage.siteMonitor=http://qbittorrent:8080
        - homepage.weight=21
        - homepage.widget.type=qbittorrent
        - homepage.widget.url=https://pt.${DOMAIN_SWARM}:${EXTERNAL_PORT}
        - homepage.widget.username=${QB_USERNAME}
        - homepage.widget.password=${QB_PASSWORD}
      <<: [*deploy-common-ref, *placement-default-ref]

  # ------------------------------------------------------------
  # iVentoy远程引导系统
  # ------------------------------------------------------------
  iventoy:
    <<: *service-common-ref
    image: ziggyds/iventoy:1.0.20
    ports:
      - 26000:26000
      - 16000:16000
      - 10809:10809
      - 67:67/udp
      - 69:69/udp
    environment:
      <<: *env-common-ref
      AUTO_START_PXE: "true" # optional, true by default
    volumes:
      - nfs_iventoy_iso:/app/iso
      - nfs_iventoy_config:/app/data
      - nfs_iventoy_log:/app/log
    logging:
      driver: fluentd
      options:
        tag: docker.resource.iventoy
        fluentd-async-connect: "true"
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.iventoy.rule=Host(`iventoy.${DOMAIN_SWARM}`,`nocoiventoybase.${DOMAIN_EMERGENCY}`)
        - traefik.http.routers.iventoy.entrypoints=websecure
        - traefik.http.routers.iventoy.service=iventoy
        - traefik.http.routers.iventoy.middlewares=auth,normal-chain@file
        - traefik.http.services.iventoy.loadbalancer.server.port=26000
        - homepage.group=Application
        - homepage.name=iVentoy
        - homepage.icon=iventoy.png
        - homepage.href=https://iventoy.${DOMAIN_SWARM}:${EXTERNAL_PORT}/
        - homepage.description=iVentoy远程引导系统
        - homepage.siteMonitor=http://iventoy:26000
        - homepage.weight=20
      <<: [*deploy-common-ref, *placement-default-ref]
  # ------------------------------------------------------------
  # IYUU
  # ------------------------------------------------------------
  # iyuu:
  #   image: iyuucn/iyuuplus:latest
    # <<: *service-common-ref
  #   environment:
  #     # 直接使用Portainer容器内的环境变量
  #     TZ: ${TZ}
  #   volumes:
  #     - nfs_iyuu_src:/IYUU
  #     - nfs_iyuu_tr:/tr
  #   deploy:
  #     labels:
  #       - traefik.enable=true
  #       - traefik.http.routers.iyuu.rule=Host(`iyuu.${DOMAIN_SWARM}`)
  #       - traefik.http.routers.iyuu.entrypoints=websecure
  #       - traefik.http.routers.iyuu.service=iyuu
  #       - traefik.http.routers.iyuu.middlewares=normal-chain@file
  #       - traefik.http.services.iyuu.loadbalancer.server.port=8787
  #       - homepage.group=Application
  #       - homepage.name=IYUU
  #       - homepage.icon=transmission.png
  #       - homepage.href=https://iyuu.${DOMAIN_SWARM}:${EXTERNAL_PORT}/
  #       - homepage.description=PT辅种
  #       - homepage.siteMonitor=http://transmission:8787
  #       - homepage.weight=21
  #    <<: [*deploy-common-ref, *placement-default-ref]

  # ------------------------------------------------------------
  # BaiduPCS
  # ------------------------------------------------------------
  # baidupcs:
  #   image: oldiy/baidupcs:latest
    # <<: *service-common-ref
  #   environment:
  #     # 直接使用Portainer容器内的环境变量
  #     PUID: ${TR_PUID}
  #     PGID: ${TR_PGID}
  #     TZ: ${TZ}
  #   volumes:
  #     - nfs_baidupcs_config:/root/.config/BaiduPCS-Go
  #     - nfs_baidupcs_client:/opt/BaiduPCS
  #     - nfs_baidupcs_download:/root/Downloads
  #   deploy:
  #     labels:
  #       - traefik.enable=true
  #       - traefik.http.routers.baidupcs.rule=Host(`baidupcs.${DOMAIN_SWARM}`)
  #       - traefik.http.routers.baidupcs.entrypoints=websecure
  #       - traefik.http.routers.baidupcs.service=baidupcs
  #       - traefik.http.routers.baidupcs.middlewares=normal-chain@file
  #       - traefik.http.services.baidupcs.loadbalancer.server.port=5299
  #       - homepage.group=Application
  #       - homepage.name=BaiduPCS
  #       - homepage.icon=https://www.${DOMAIN_NAS}:${EXTERNAL_PORT}/images/services/baidupan.png
  #       - homepage.href=https://baidupcs.${DOMAIN_SWARM}:${EXTERNAL_PORT}/
  #       - homepage.description=百度云盘下载器
  #       - homepage.siteMonitor=http://baidupcs:5299
  #       - homepage.weight=21
  #    <<: [*deploy-common-ref, *placement-default-ref]

networks:
  network_cluster:
    external: true

volumes:
  # NFS
  nfs_transmission_config:
    driver: local
    driver_opts:
      <<: *driver-common-ref
      device: :${NFS_DEVICE}/application/download/transmission/config
  nfs_transmission_main_downloads:
    driver: local
    driver_opts:
      <<: *driver-media-main-ref
      device: :${MEDIA_DEVICE}
  nfs_transmission_ext_downloads:
    driver: local
    driver_opts:
      <<: *driver-media-ext-ref
      device: :${MEDIA_DEVICE}
  nfs_transmission_watch:
    driver: local
    driver_opts:
      <<: *driver-media-main-ref
      device: :${MEDIA_DEVICE}/watch
  nfs_qbittorrent_config:
    driver: local
    driver_opts:
      <<: *driver-common-ref
      device: :${NFS_DEVICE}/application/download/qbittorrent/config
  nfs_qbittorrent_main_downloads:
    driver: local
    driver_opts:
      <<: *driver-media-main-ref
      device: :${MEDIA_DEVICE}
  nfs_qbittorrent_ext_downloads:
    driver: local
    driver_opts:
      <<: *driver-media-ext-ref
      device: :${MEDIA_DEVICE}
  nfs_iyuu_src:
    driver: local
    driver_opts:
      <<: *driver-common-ref
      device: :${NFS_DEVICE}/application/download/iyuu/src
  nfs_iyuu_tr:
    driver: local
    driver_opts:
      <<: *driver-common-ref
      device: :${NFS_DEVICE}/application/download/transmission/config/torrents
  nfs_baidupcs_client:
    driver: local
    driver_opts:
      <<: *driver-common-ref
      device: :${NFS_DEVICE}/application/download/baidupcs/client
  nfs_baidupcs_config:
    driver: local
    driver_opts:
      <<: *driver-common-ref
      device: :${NFS_DEVICE}/application/download/baidupcs/config
  nfs_baidupcs_download:
    driver: local
    driver_opts:
      <<: *driver-common-ref
      device: :${DOWNLOAD_DEVICE}/baidupcs
  nfs_iventoy_iso:
    driver: local
    driver_opts:
      <<: *driver-iso-ref
      device: :${DOWNLOAD_DEVICE}/iso      
  nfs_iventoy_config:
    driver: local
    driver_opts:
      <<: *driver-common-ref
      device: :${NFS_DEVICE}/resource/iventoy/config
  nfs_iventoy_log:
    driver: local
    driver_opts:
      <<: *driver-common-ref
      device: :${NFS_DEVICE}/resource/iventoy/log
...