# Update Time: 2024-2-1 21:10
version: "3.4"

services:
  # Transmission
  transmission:
    image: chisbread/transmission:latest
    networks: [network_cluster]
    restart: on-failure  
    environment:
      # 直接使用Portainer容器内的环境变量
      PUID: ${TR_PUID}
      PGID: ${TR_PGID}
      USERNAME: ${TR_USERNAME}       
      PASSWORD: ${TR_PASSWORD}
      TZ: ${TZ}
    volumes:
      - nfs_transmission_config:/config
      - nfs_transmission_main_downloads:/media
      - nfs_transmission_ext_downloads:/media_ext
      - nfs_transmission_watch:/watch
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.transmission.rule=Host(`pt.${DOMAIN_SWARM}`,`pt.${DOMAIN_EMERGENCY}`)"
        - "traefik.http.routers.transmission.entrypoints=websecure"
        - "traefik.http.routers.transmission.service=transmission"
        - "traefik.http.routers.transmission.middlewares=auth,normal-chain@file"
        - "traefik.http.services.transmission.loadbalancer.server.port=9091"
        # - "traefik.tcp.routers.torrent.rule=HostSNI(`*`)"
        # - "traefik.tcp.routers.torrent.entrypoints=torrent"
        # - "traefik.tcp.routers.torrent.service=torrent"
        # - "traefik.tcp.services.torrent.loadbalancer.server.port=51413"   
        - homepage.group=Application
        - homepage.name=Transmission
        - homepage.icon=transmission.png
        - homepage.href=https://pt.${DOMAIN_SWARM}:${EXTERNAL_PORT}/
        - homepage.description=PT下载器
        - homepage.siteMonitor=http://transmission:9091
        - homepage.weight=20
        - homepage.widget.type=transmission
        - homepage.widget.url=https://pt.${DOMAIN_SWARM}:${EXTERNAL_PORT}    
        - homepage.widget.username=${TR_USERNAME}
        - homepage.widget.password=${TR_PASSWORD}
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.type == vm
          - node.labels.download == true
    logging:
      driver: fluentd
      options:
        tag: docker.resource.transmissionn
        fluentd-async-connect: "true"  

  # Qbittorrent
  qbittorrent:
    image: linuxserver/qbittorrent
    networks: [network_cluster]
    restart: on-failure  
    environment:
      # 直接使用Portainer容器内的环境变量
      PUID: ${QB_PUID}
      PGID: ${QB_PGID}
      # UMASK_SET: 022    # （可选）默认022
      # WEBUI_PORT: 4  # WEB UI 端口 
      TZ: ${TZ}
    volumes:
      - nfs_qbittorrent_config:/config
      - nfs_qbittorrent_main_downloads:/media
      - nfs_qbittorrent_ext_downloads:/media_ext
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.qbittorrent.rule=Host(`qb.${DOMAIN_SWARM}`,`qb.${DOMAIN_EMERGENCY}`)"
        - "traefik.http.routers.qbittorrent.entrypoints=websecure"
        - "traefik.http.routers.qbittorrent.service=qbittorrent"
        - "traefik.http.routers.qbittorrent.middlewares=auth,normal-chain@file"
        - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
        # - "traefik.tcp.routers.qb_pt.rule=HostSNI(`*`)"
        # - "traefik.tcp.routers.qb_pt.entrypoints=qb_pt"
        # - "traefik.tcp.routers.qb_pt.service=qb_pt"
        # - "traefik.tcp.services.qb_pt.loadbalancer.server.port=6881"   
        - homepage.group=Application
        - homepage.name=Qbittorrent
        - homepage.icon=qbittorrent.png
        - homepage.href=https://qb.${DOMAIN_SWARM}:${EXTERNAL_PORT}/
        - homepage.description=PT下载器
        - homepage.siteMonitor=http://qbittorrent:8080
        - homepage.weight=21
        - homepage.widget.type=qbittorrent
        - homepage.widget.url=https://pt.${DOMAIN_SWARM}:${EXTERNAL_PORT}    
        - homepage.widget.username=${QB_USERNAME}
        - homepage.widget.password=${QB_PASSWORD}
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.type == vm
          - node.labels.download == true

  # IYUU
  # iyuu:
  #   image: iyuucn/iyuuplus:latest
  #   networks: [network_cluster]
  #   restart: on-failure  
  #   environment:
  #     # 直接使用Portainer容器内的环境变量
  #     TZ: ${TZ}
  #   volumes:
  #     - nfs_iyuu_src:/IYUU
  #     - nfs_iyuu_tr:/tr
  #   deploy:
  #     labels:
  #       - "traefik.enable=true"
  #       - "traefik.http.routers.iyuu.rule=Host(`iyuu.${DOMAIN_SWARM}`)"
  #       - "traefik.http.routers.iyuu.entrypoints=websecure"
  #       - "traefik.http.routers.iyuu.service=iyuu"
  #       - "traefik.http.routers.iyuu.middlewares=normal-chain@file"
  #       - "traefik.http.services.iyuu.loadbalancer.server.port=8787"  
  #       - homepage.group=Application
  #       - homepage.name=IYUU
  #       - homepage.icon=transmission.png
  #       - homepage.href=https://iyuu.${DOMAIN_SWARM}:${EXTERNAL_PORT}/
  #       - homepage.description=PT辅种
  #       - homepage.siteMonitor=http://transmission:8787
  #       - homepage.weight=21
  #     mode: replicated
  #     replicas: 1
  #     placement:
  #       constraints:
  #         - node.labels.type == vm
  #         - node.labels.download == true
  # BaiduPCS
  # baidupcs:
  #   image: oldiy/baidupcs:latest
  #   networks: [network_cluster]
  #   restart: on-failure  
  #   environment:
  #     # 直接使用Portainer容器内的环境变量
  #     PUID: ${TR_PUID}
  #     PGID: ${TR_PGID}
  #     TZ: ${TZ}    
  #   volumes:
  #     - nfs_baidupcs_config:/root/.config/BaiduPCS-Go
  #     - nfs_baidupcs_client:/opt/BaiduPCS
  #     - nfs_baidupcs_download:/root/Downloads
  #   deploy:
  #     labels:
  #       - "traefik.enable=true"
  #       - "traefik.http.routers.baidupcs.rule=Host(`baidupcs.${DOMAIN_SWARM}`)"
  #       - "traefik.http.routers.baidupcs.entrypoints=websecure"
  #       - "traefik.http.routers.baidupcs.service=baidupcs"
  #       - "traefik.http.routers.baidupcs.middlewares=normal-chain@file"
  #       - "traefik.http.services.baidupcs.loadbalancer.server.port=5299"
  #       - homepage.group=Application
  #       - homepage.name=BaiduPCS
  #       - homepage.icon=https://www.waylon.wang:4/images/services/baidupan.png
  #       - homepage.href=https://baidupcs.${DOMAIN_SWARM}:${EXTERNAL_PORT}/
  #       - homepage.description=百度云盘下载器
  #       - homepage.siteMonitor=http://baidupcs:5299
  #       - homepage.weight=21        
  #     mode: replicated
  #     replicas: 1
  #     placement:
  #       constraints:
  #         - node.labels.type == vm
  #         - node.labels.download == true            


networks:
  network_cluster:
    external: true

x-common-keys-volume: &common-keys-volume
  type: nfs
  o: addr=${NFS_SERVER},rw,nfsvers=4

x-common-media-main-volume: &common-media-main-volume
  type: nfs
  o: addr=${MEDIA_SERVER},rw,nfsvers=4

x-common-media-ext-volume: &common-media-ext-volume
  type: nfs
  o: addr=${MEDIA_EXT_SERVER},rw,nfsvers=4

volumes:
  # NFS     
  nfs_transmission_config:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/application/download/transmission/config
  nfs_transmission_main_downloads:
    driver: local
    driver_opts:
      <<: *common-media-main-volume
      device: :${MEDIA_DEVICE}   
  nfs_transmission_ext_downloads:
    driver: local
    driver_opts:
      <<: *common-media-ext-volume
      device: :${MEDIA_DEVICE}       
  nfs_transmission_watch:
    driver: local
    driver_opts:
      <<: *common-media-main-volume
      device: :${MEDIA_DEVICE}/watch    
  nfs_qbittorrent_config:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/application/download/qbittorrent/config
  nfs_qbittorrent_main_downloads:
    driver: local
    driver_opts:
      <<: *common-media-main-volume
      device: :${MEDIA_DEVICE}   
  nfs_qbittorrent_ext_downloads:
    driver: local
    driver_opts:
      <<: *common-media-ext-volume
      device: :${MEDIA_DEVICE}       
  nfs_iyuu_src:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/application/download/iyuu/src  
  nfs_iyuu_tr:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/application/download/transmission/config/torrents            
  nfs_baidupcs_client:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/application/download/baidupcs/client   
  nfs_baidupcs_config:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/application/download/baidupcs/config
  nfs_baidupcs_download:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${DOWNLOAD_DEVICE}/baidupcs                